spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        ddl-auto: update # 또는 create, create-drop 등
        format_sql: true
    defer-datasource-initialization: true
  datasource:
    url: jdbc:h2:mem:testdb
  h2: #user: CaffeineLIL, password: 123456 잠깐 테스트할려고 이렇게해놈
    console:
      enabled: true